# Generated by Django 5.2.12 on 2026-04-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_acessorio_cor_modelo_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
