# Generated by Django 5.2.12 on 2026-04-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_veiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'Acessório', 'verbose_name_plural': 'Acessórios'},
        ),
    ]
