# Generated by Django 5.2.12 on 2026-04-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_acessorio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='acessorios',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='acessorios',
            field=models.ManyToManyField(blank=True, null=True, related_name='veiculos', to='core.acessorio'),
        ),
    ]
